# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'graph-ql' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for graph-ql
  pod 'Apollo', '0.7.0-alpha.11'
  #pod 'Apollo', '~> 0.6.0'

end
